apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    name: api-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    name: api-gateway